use_frameworks!

platform :ios, '9.0'

target 'ShutDownCellTimerLib_Example' do
  pod 'ShutDownCellTimerLib', :path => '../'

  target 'ShutDownCellTimerLib_Tests' do
    inherit! :search_paths

    
  end
end
